version: '3.9'

services:
  web-server:
    build: .
    container_name: web-server-apache
    ports:
      - "8090:80"
    volumes:
      - ./app:/usr/local/apache2/htdocs
    networks:
      - net-test

networks:
 net-test:
  driver: bridge